version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: urban_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
